name: Formatting

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deps
        run: |
          sudo apt-get update

          # Basic
          sudo apt-get install curl
          sudo apt-get install wget
          sudo apt-get install build-essential

          # Tauri
          sudo apt-get install libwebkit2gtk-4.0-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libayatana-appindicator3-dev
          sudo apt-get install librsvg2-dev

          # Additional
          sudo apt-get install libxcb-shape0-dev
          sudo apt-get install libxcb-xfixes0-dev
          sudo apt-get install libxcb1-dev
          sudo apt-get install libxkbcommon-dev
          sudo apt-get install libwebkit2gtk-4.0
          sudo apt-get install libudev-dev
          sudo apt-get install libsdl2-dev
          sudo apt-get install libasound2-dev

      - name: Check Format
        run: cargo fmt --all -- --check
        working-directory: src-tauri
    
      - name: Check Warnings
        run: cargo clippy -- -D warnings
        working-directory: src-tauri
