name: Linux Build

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Update Node.js
        run: npm install

      - name: Install Tauri Deps
        run: |
          sudo apt update

          sudo apt-get install curl
          sudo apt-get install wget
          sudo apt-get install build-essential

          sudo apt-get install libwebkit2gtk-4.0-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libayatana-appindicator3-dev
          sudo apt-get install librsvg2-dev
      
      - name: Install LibTorch
        run: |
          wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.13.0%2Bcpu.zip
          unzip libtorch-shared-with-deps-1.13.0+cpu.zip
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/libtorch/lib

      - name: Tauri Build
        run: npx tauri build --verbose
