name: Linux Test

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Update Node.js
        run: npm install

      - name: Create Dist Directory
        run: sudo mkdir dist

      - name: Install Tauri Deps
        run: |
          sudo apt update

          sudo apt-get install curl
          sudo apt-get install wget
          sudo apt-get install build-essential

          sudo apt-get install libwebkit2gtk-4.0-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libayatana-appindicator3-dev
          sudo apt-get install librsvg2-dev

          sudo apt-get install libxcb-shape0-dev
          sudo apt-get install libxcb-xfixes0-dev
          sudo apt-get install libxcb1-dev
          sudo apt-get install libxkbcommon-dev
          sudo apt-get install libwebkit2gtk-4.0
          sudo apt-get install libudev-dev
          sudo apt-get install libsdl2-dev
          sudo apt-get install libasound2-dev
      
      - name: Install LibTorch
        run: |
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.13.0%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-1.13.0+cpu.zip
          cp -a libtorch/. /usr/local/lib

      - name: LDConfig Reload
        run: |
          sudo ldconfig -p
          sudo ldconfig -v

      # - name: Build Rust Debug
      #   run: cargo build --verbose --verbose
      #   working-directory: src-tauri
      
      # - name: Build Rust Release
      #   run: cargo build --release --verbose --verbose
      #   working-directory: src-tauri
      
      - name: Test
        run: cargo test --verbose --verbose
        working-directory: src-tauri
