name: MacOS Bash Setup

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Script
        run: sudo ./scripts/setup.sh
