name: MacOS Release

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Update Node.js
        run: npm install

      - name: Create Dist Directory
        run: sudo mkdir dist
      
      - name: Install LibTorch
        run: |
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.13.1%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-1.13.1+cpu.zip

      - name: Test
        run: cargo test --verbose --verbose
        working-directory: src-tauri

      - name: Build
        run: npx tauri build --verbose
      
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: mascoty-taurine-build
          path: src-tauri/target/release/bundle/dmg/*.dmg

      # - name: Create Release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
