name: Windows Build

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Update Node.js
        run: npm install

      - name: Install LibTorch
        run: |
          choco install unzip

          curl https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.13.1%2Bcpu.zip --output libtorch.zip
          unzip libtorch.zip

          ls
          ls -Path libtorch
          ls -Path libtorch\lib

      - name: Add LibTorch to PATH
        run: |
          $CURR = Get-Location
          echo $CURR

          $TORCH = "libtorch\lib"
          $JOINED = Join-Path $CURR $TORCH
          
          $env:PATH = "$JOINED;" + $env:PATH
          echo $env:PATH

      - name: Tauri Build
        run: npx tauri build --verbose

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: mascoty-taurine-build
          path: src-tauri/target/release/bundle/msi/*.msi
